name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev-*
    paths-ignore:
      - "*.md"
      - "*.yml"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.yml"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: package.json

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: package.json

      - name: Install dependencies
        run: npm i

      - name: Playground prepare
        run: npm run dev:prepare

      - name: Test
        run: npm run test
